from .wan_tiled_sampler import (
    NODE_CLASS_MAPPINGS as WAN_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WAN_DISPLAY_MAPPINGS,
)
from .ltx_tiled_sampler import (
    NODE_CLASS_MAPPINGS as LTX_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LTX_DISPLAY_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {**WAN_CLASS_MAPPINGS, **LTX_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**WAN_DISPLAY_MAPPINGS, **LTX_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
